spring.application.name=crypto-recommendation-service
crypto.prices.directory=classpath:data/prices
#crypto.prices.directory=C:/Users/steli/Downloads/crypto-recommendation-service/crypto-recommendation-service/src/main/resources/data/prices

