spring.application.name=crypto-recommendation-service
crypto.prices.directory=classpath:data/prices

#Ratelimit configuration
ratelimit.maxTokens = 10
ratelimit.refilledTokens = 10
ratelimit.refillPeriod = 1
